-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgyR2FcoRchlUVNS7VEFXQ//v7y7VzCAYWNzUoXjWWLsmgCgYIKoZIzj0DAQehRANCAATNAExgQ+MJRp32MJAOiwrGU75KYhZG4oAsAAqavWTuxYG9ddsoxUN5HlTSbVFFRJ5HLUQJaSJIa+sj1Su8yNUh
-----END PRIVATE KEY-----